# Generated by Django 5.0 on 2023-12-08 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('cas_number', models.CharField(max_length=100)),
                ('purch_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('purch_cod', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('sell_cod', models.CharField(max_length=50)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('product_type', models.CharField(choices=[('NATIONAL', 'NACIONAL'), ('IMPORTED', 'IMPORTADO')], max_length=10)),
                ('quantity_type', models.CharField(choices=[('UN', 'UN'), ('PK', 'PK')], max_length=2)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='project.supplier')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name', 'purch_cod'),
            },
        ),
    ]
