# Generated by Django 5.0 on 2023-12-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('sell_cod', models.FloatField()),
                ('purch_cod', models.FloatField()),
                ('cas_number', models.FloatField()),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('purch_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('product_type', models.CharField(choices=[('national', 'nacional'), ('imported', 'importado')], max_length=10)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='project.supplier')),
            ],
        ),
    ]
