# Generated by Django 5.0 on 2023-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_product_options_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('nacional', 'nacional'), ('importado', 'importado')], max_length=10),
        ),
    ]
